# Generated by Django 4.2.8 on 2024-01-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akhila',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
